### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by syptic** [qiwenkevin/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Missing keystroke count.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Great job!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page
```

**Comment by qiwenkevin** [comment]
Keystroke count added

**Comment by qiwenkevin** [comment]
Hi, 

After the last regrade request, the regrader said that "just saying we can type the command and then use arrow key doesn't reduce the keystrokes as you have to type it first to use the arrow up key to repeat the command."

But what our lab did at the time was to simply count how many keystrokes it would take to rerun the command with the least amount of keystrokes and we all agreed to the two keystrokes for rerunning the command. 

And so I'm confused as to how to optimise the the keystroke count of the command as we didn't talk about that during our lab as I thought this is for that same task in lab.
